<a href="https://colab.research.google.com/github/Adnan5603/brainybeam-task/blob/main/task4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Calculate the determinant of a square matrix using numpy.


In [1]:
import numpy as np

In [2]:
A = np.array([[2, 4, 1],
              [3, 1, 5],
              [1, 2, 3]])

In [3]:
print("Matrix A:")
print(A)

Matrix A:
[[2 4 1]
 [3 1 5]
 [1 2 3]]


In [4]:
det_A = np.linalg.det(A)

In [5]:
print("\nDeterminant of A:", det_A)


Determinant of A: -25.000000000000007


In [6]:
print("Rounded Determinant:", round(det_A, 2))

Rounded Determinant: -25.0
